##1.Tokenization
Đọc thêm ở đây: https://huggingface.co/docs/transformers/main_classes/tokenizer#tokenizer
**Tokenization:**

Tokenization là bước quan trọng trong xử lý ngôn ngữ tự nhiên (NLP), giúp chia nhỏ văn bản thành các đơn vị (tokens) như từ hoặc câu. Dưới đây là một số thông tin và ví dụ về cách sử dụng tokenizer:

### Các loại Tokenizer

1. **Word Tokenizer**: Chia nhỏ văn bản thành các từ.
2. **Sentence Tokenizer**: Chia văn bản thành các câu.
3. **Subword Tokenizer**: Chia từ thành các phần nhỏ hơn (như Byte-Pair Encoding hay WordPiece).
### **Một số lưu ý**
Tokenization có thể ảnh hưởng lớn đến hiệu suất của mô hình, vì vậy hãy thử nghiệm với các loại tokenizer khác nhau.
Đảm bảo xử lý các ký tự đặc biệt và ngôn ngữ khác nhau đúng cách.

In [ ]:
pip install sacremoses


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 15.4 MB/s eta 0:00:00


In [ ]:
import torch
tokenizer = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-base-cased')

Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_main
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [ ]:
text_1 = "I understand equations, both the simple and quadratical."
text_2 = "What kind of equations do I understand?"
#Encode from word to number
indexed_tokens = tokenizer.encode(text_1,text_2,add_special_tokens=True)
indexed_tokens

[101,
 146,
 2437,
 11838,
 117,
 1241,
 1103,
 3014,
 1105,
 186,
 18413,
 21961,
 1348,
 119,
 102,
 1327,
 1912,
 1104,
 11838,
 1202,
 146,
 2437,
 136,
 102]

In [ ]:
tokenizer.convert_ids_to_tokens([str(token) for token in indexed_tokens]) # Đoạn code này chuyển các mã ở trên thành các token tương ứng dưới dạng chuỗi văn bản.

['[CLS]',
 'I',
 'understand',
 'equations',
 ',',
 'both',
 'the',
 'simple',
 'and',
 'q',
 '##uad',
 '##ratic',
 '##al',
 '.',
 '[SEP]',
 'What',
 'kind',
 'of',
 'equations',
 'do',
 'I',
 'understand',
 '?',
 '[SEP]']

In [ ]:
tokenizer.decode(indexed_tokens) #Đoạn code này khôi phục đoạn mã ở trên về văn bản gốc
#SEP: Seperator
#CLS: Classification.

'[CLS] I understand equations, both the simple and quadratical. [SEP] What kind of equations do I understand? [SEP]'

##2.Segmenting Text
Segmenting text" (phân đoạn văn bản) là quá trình chia nhỏ một đoạn văn bản thành các phần nhỏ hơn, thường là các câu, từ, hoặc đoạn văn, để dễ dàng xử lý và phân tích. Dưới đây là một số khía cạnh quan trọng của phân đoạn văn bản:

Các loại phân đoạn văn bản:

Phân đoạn câu:

Phân đoạn từ:

Phân đoạn đoạn văn:
Chia văn bản thành các đoạn văn. Một đoạn văn có thể bao gồm nhiều câu và thường được phân tách bằng một dòng trống hoặc dấu chấm.

Tác dụng của phân đoạn văn bản
Tăng cường khả năng phân tích: Phân đoạn văn bản giúp cho các mô hình xử lý ngôn ngữ tự nhiên (NLP) dễ dàng hơn trong việc hiểu và phân tích nội dung, vì các mô hình thường hoạt động tốt hơn với các đơn vị nhỏ hơn.
Chuẩn bị dữ liệu: Trong các tác vụ như phân loại văn bản, phân tích cảm xúc, hoặc trả lời câu hỏi, việc phân đoạn văn bản là bước quan trọng để chuẩn bị dữ liệu đầu vào cho mô hình.
Cải thiện độ chính xác: Việc phân đoạn chính xác có thể cải thiện hiệu suất của các thuật toán máy học và các mô hình học sâu, vì nó giúp mô hình nắm bắt được ngữ cảnh và cấu trúc của văn bản tốt hơn.
Công cụ và kỹ thuật
Có nhiều công cụ và thư viện hỗ trợ phân đoạn văn bản, bao gồm:

NLTK: Thư viện Python cho xử lý ngôn ngữ tự nhiên, cung cấp các công cụ phân đoạn câu và từ.
spaCy: Một thư viện khác cho NLP, hỗ trợ phân đoạn văn bản và nhiều tác vụ khác.
BERT và các mô hình Transformer: Các mô hình này thường yêu cầu đầu vào được phân đoạn trước khi xử lý.


In [ ]:
cls_token = 101
sep_token = 102

def get_segments_ids(indexed_tokens):
  segment_ids = []
  segment_id = 0
  for token in indexed_tokens:
    if token == sep_token:
      segment_id += 1
    segment_ids.append(segment_id)
  segment_ids[-1] -=1 #Last [SEP] is ignored
  return torch.tensor([segment_ids]), torch.tensor([indexed_tokens])

In [ ]:
segment_tensors, tokens_tensors = get_segments_ids(indexed_tokens)
print(segment_tensors)
print(tokens_tensors)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  101,  1045,  3305, 11380,  1010,  2119,  1996,  3722,  1998, 17718,
         23671,  2389,  1012,   102,  2054,  2785,  1997, 11380,  2079,  1045,
          3305,  1029,   102]])


##3.Text Masking
Text Masking (mặt nạ văn bản) là một kỹ thuật trong xử lý ngôn ngữ tự nhiên (NLP) và học máy, nơi thông tin nhạy cảm hoặc không cần thiết được che giấu (hoặc "mặt nạ") để bảo vệ dữ liệu hoặc để hướng dẫn mô hình học cách dự đoán các phần của dữ liệu đó. Dưới đây là một số khía cạnh chính của text masking:

Mục đích của Text Masking
Bảo mật dữ liệu:
Giúp bảo vệ thông tin nhạy cảm, như thông tin cá nhân, số thẻ tín dụng, hoặc dữ liệu y tế, bằng cách thay thế hoặc che giấu các phần của văn bản.
Đào tạo mô hình:
Trong một số mô hình học sâu, như BERT, text masking được sử dụng để huấn luyện mô hình dự đoán các từ bị thiếu hoặc bị che giấu trong một câu. Điều này giúp mô hình hiểu ngữ cảnh và mối quan hệ giữa các từ trong văn bản.
Cách thức hoạt động
Che giấu từ: Trong quá trình huấn luyện, một số từ trong câu sẽ được thay thế bằng một token đặc biệt (thường là [MASK]). Mô hình sau đó sẽ học cách dự đoán từ bị che giấu dựa trên các từ còn lại trong câu. Ví dụ:
Câu gốc: "Tôi thích ăn bánh pizza."
Câu sau khi mặt nạ: "Tôi thích ăn [MASK] pizza."
Dự đoán từ: Mô hình sẽ cố gắng dự đoán từ "bánh" dựa trên ngữ cảnh của các từ khác trong câu.
Ứng dụng
Huấn luyện mô hình NLP: Text masking là một phần quan trọng trong quá trình huấn luyện nhiều mô hình NLP hiện đại, giúp cải thiện khả năng dự đoán và hiểu ngữ nghĩa.
Bảo vệ thông tin nhạy cảm: Trong các ứng dụng mà dữ liệu cá nhân cần được bảo vệ, text masking có thể được sử dụng để che giấu thông tin trước khi lưu trữ hoặc chia sẻ.
Xử lý văn bản: Trong các tác vụ như phân loại văn bản hoặc phân tích cảm xúc, text masking có thể giúp làm nổi bật các phần quan trọng của văn bản mà không tiết lộ tất cả thông tin.

In [ ]:
tokenizer.mask_token

'[MASK]'

In [ ]:
tokenizer.mask_token_id

103

In [ ]:
masked_index = 5

In [ ]:
indexed_tokens[masked_index] = tokenizer.mask_token_id
tokens_tensors = torch.tensor([indexed_tokens])
tokenizer.decode(indexed_tokens)

'[CLS] 正town curiosity 天 [MASK] deep organizations Club investigators sprawled Maybe 夫 [SEP] Island pretty 1990 curiosity range 正town 戸 [SEP]'

In [ ]:
masked_lm_model = torch.hub.load('huggingface/pytorch-transformers', 'modelForMaskedLM', 'bert-base-cased')

Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_main


model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls

In [ ]:
masked_lm_model #Check the architecture of the model

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [ ]:
embedding_table = next(masked_lm_model.bert.embeddings.word_embeddings.parameters())
embedding_table

Parameter containing:
tensor([[-0.0005, -0.0416,  0.0131,  ..., -0.0039, -0.0335,  0.0150],
        [ 0.0169, -0.0311,  0.0042,  ..., -0.0147, -0.0356, -0.0036],
        [-0.0006, -0.0267,  0.0080,  ..., -0.0100, -0.0331, -0.0165],
        ...,
        [-0.0064,  0.0166, -0.0204,  ..., -0.0418, -0.0492,  0.0042],
        [-0.0048, -0.0027, -0.0290,  ..., -0.0512,  0.0045, -0.0118],
        [ 0.0313, -0.0297, -0.0230,  ..., -0.0145, -0.0525,  0.0284]],
       requires_grad=True)

In [ ]:
embedding_table.shape

torch.Size([28996, 768])

In [ ]:
with torch.no_grad():
  predictions = masked_lm_model(tokens_tensors, token_type_ids=segment_tensors)
predictions

MaskedLMOutput(loss=None, logits=tensor([[[ -7.3832,  -7.2504,  -7.4539,  ...,  -6.0597,  -5.7928,  -6.2133],
         [ -6.7681,  -6.7896,  -6.8316,  ...,  -5.4655,  -5.4048,  -6.0682],
         [ -7.7323,  -7.9597,  -7.7348,  ...,  -5.7611,  -5.3566,  -4.3361],
         ...,
         [ -6.1213,  -6.3311,  -6.4144,  ...,  -5.8884,  -4.1157,  -3.1189],
         [-12.3216, -12.4479, -11.9787,  ..., -10.6539,  -8.7396, -11.0487],
         [-13.4115, -13.7876, -13.5183,  ..., -10.6359, -11.6582, -10.9009]]]), hidden_states=None, attentions=None)

In [ ]:
predictions[0].shape

torch.Size([1, 24, 28996])

In [ ]:
#Get the predicted token
predicted_index = torch.argmax(predictions[0][0],dim = 1)[masked_index].item()

In [ ]:
predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
predicted_token

'both'

In [ ]:
tokenizer.decode(indexed_tokens)

'[CLS] I understand equations, [MASK] the simple and quadratical. [SEP] What kind of equations do I understand? [SEP]'

##4.Question and Answering

In [ ]:
text_1 = "I understand equations, both the simple and quadratical."
text_2 = "What kind of equations do I understand?"

question_answering_tokenizer = torch.hub.load('huggingface/pytorch-transformers', 'tokenizer', 'bert-large-uncased-whole-word-masking-finetuned-squad')
indexed_tokens = question_answering_tokenizer.encode(text_1, text_2, add_special_tokens=True)
segments_tensors, tokens_tensor = get_segments_ids(indexed_tokens)

Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_main


In [ ]:
question_answering_model = torch.hub.load('huggingface/pytorch-transformers', 'modelForQuestionAnswering', 'bert-large-uncased-whole-word-masking-finetuned-squad')

Using cache found in /root/.cache/torch/hub/huggingface_pytorch-transformers_main


model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-large-uncased-whole-word-masking-finetuned-squad were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
# Predict the start and end positions logits
with torch.no_grad():
    out = question_answering_model(tokens_tensor, token_type_ids=segments_tensors)
out

QuestionAnsweringModelOutput(loss=None, start_logits=tensor([[-5.5943, -4.2960, -5.2682, -1.2511, -6.8350, -0.3992,  2.2274,  2.4654,
         -6.6066,  2.5014, -4.4613, -4.8040, -7.8383, -5.5944, -4.7833, -6.9730,
         -7.1477, -5.2967, -7.4825, -6.7737, -6.8806, -8.6612, -5.5944]]), end_logits=tensor([[-0.7409, -5.3478, -4.2317, -0.0275, -2.6293, -5.9589, -2.8828,  2.7770,
         -4.8512, -2.2092, -2.2413,  4.4412, -0.7181, -0.7411, -3.8988, -5.3865,
         -5.0452, -4.4974, -6.3098, -5.5937, -5.5562, -5.3034, -0.7412]]), hidden_states=None, attentions=None)

In [ ]:
out.start_logits

tensor([[-5.5943, -4.2960, -5.2682, -1.2511, -6.8350, -0.3992,  2.2274,  2.4654,
         -6.6066,  2.5014, -4.4613, -4.8040, -7.8383, -5.5944, -4.7833, -6.9730,
         -7.1477, -5.2967, -7.4825, -6.7737, -6.8806, -8.6612, -5.5944]])

In [ ]:
out.end_logits

tensor([[-0.7409, -5.3478, -4.2317, -0.0275, -2.6293, -5.9589, -2.8828,  2.7770,
         -4.8512, -2.2092, -2.2413,  4.4412, -0.7181, -0.7411, -3.8988, -5.3865,
         -5.0452, -4.4974, -6.3098, -5.5937, -5.5562, -5.3034, -0.7412]])

In [ ]:
answer_sequence = indexed_tokens[torch.argmax(out.start_logits):torch.argmax(out.end_logits)+1]
answer_sequence

[17718, 23671, 2389]

In [ ]:
question_answering_tokenizer.convert_ids_to_tokens(answer_sequence)

['quad', '##ratic', '##al']

In [ ]:
question_answering_tokenizer.decode(answer_sequence)

'quadratical'

In [ ]:
import IPython
app = IPython.Application.instance()
app.kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}